### ISSUE TITLE
Init migration 

### ISSUE THREAD

**Issue by sepiropht** [mrusme/xbsapi#3]
i have this error 
`2023-03-03T19:27:10.198Z        DEBUG   bookmarks/create.go:86  Could not create bookmark       {"error": "Error 1146 (42S02): Table 'xbsapi.bookmarks' doesn't exist"} `

Where xbsapi is the name of my db in mysql. 
i using docker-compose

```
version: "2"
services:
  xbsapi:
    image: mrusme/xbsapi:latest
    container_name: xbsapi
    volumes:
      - ./xbsapi.toml:/etc/xbsapi.toml
    ports:
      - 8090:8000
    depends_on:
      - db-mysql
    restart: unless-stopped
  db-mysql:
    image: linuxserver/mariadb
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=xbsapi
      - MYSQL_USER=xbsapi
      - MYSQL_PASSWORD=azerty
    volumes:
      - ./mariadb:/config
    restart: unless-stopped
```
and this is my xbsapi 

` [Database]
Type = "mysql"
Connection = "xbsapi:azerty@tcp(db-mysql:3306)/xbsapi?parseTime=true" `
